name: Fetch Weather Data

# This is the schedule for the workflow, in cron syntax
on:
  schedule:
    - cron: '0 * * * *'  # Run every hour (UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  fetch_weather:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner provided by GitHub

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_weather_data.py script
        run: |
          python3 fetch_weather_data.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # Use secrets for sensitive data

      - name: Upload Weather Data to AMAZON S3
        uses: actions/upload-artifact@v2
        with:
          name: weather-data
          path: *.json  # Upload all the JSON files generated by the script
